FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache \
    libc6-compat 

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json yarn.lock* package-lock.json* ./

RUN yarn install --frozen-lockfile

COPY . .

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

CMD ["yarn", "dev"]
