// Mock data for contests
export const mockContestsData: ContestsResponse = {
  data: [
    {
      id: 'contest-1',
      title: 'Weekly Programming Contest #1',
      description:
        'A beginner-friendly weekly contest featuring algorithmic problems.',
      startTime: '2026-01-05T09:00:00.000Z',
      endTime: '2026-01-05T12:00:00.000Z',
      status: 'UPCOMING',
      isPublic: true,
      createdAt: '2025-12-28T10:00:00.000Z',
      updatedAt: '2025-12-28T10:00:00.000Z',
      createdBy: {
        id: 'user-1',
        name: 'Admin User',
        email: 'admin@hustcode.com',
      },
      _count: {
        problems: 5,
        participants: 120,
      },
    },
    {
      id: 'contest-2',
      title: 'New Year Coding Challenge',
      description: 'Celebrate the new year with exciting coding challenges!',
      startTime: '2026-01-01T00:00:00.000Z',
      endTime: '2026-01-01T06:00:00.000Z',
      status: 'RUNNING',
      isPublic: true,
      createdAt: '2025-12-25T08:00:00.000Z',
      updatedAt: '2025-12-31T23:59:00.000Z',
      createdBy: {
        id: 'user-1',
        name: 'Admin User',
        email: 'admin@hustcode.com',
      },
      _count: {
        problems: 6,
        participants: 250,
      },
    },
    {
      id: 'contest-3',
      title: 'Advanced Algorithms Contest',
      description: 'Challenge yourself with advanced algorithmic problems.',
      startTime: '2025-12-20T14:00:00.000Z',
      endTime: '2025-12-20T18:00:00.000Z',
      status: 'FINISHED',
      isPublic: true,
      createdAt: '2025-12-15T10:00:00.000Z',
      updatedAt: '2025-12-20T18:00:00.000Z',
      createdBy: {
        id: 'user-2',
        name: 'Contest Admin',
        email: 'contest@hustcode.com',
      },
      _count: {
        problems: 4,
        participants: 85,
      },
    },
    {
      id: 'contest-4',
      title: 'Dynamic Programming Masterclass',
      description: 'A contest focused on dynamic programming techniques.',
      startTime: '2025-12-15T10:00:00.000Z',
      endTime: '2025-12-15T14:00:00.000Z',
      status: 'FINISHED',
      isPublic: true,
      createdAt: '2025-12-10T12:00:00.000Z',
      updatedAt: '2025-12-15T14:00:00.000Z',
      createdBy: {
        id: 'user-1',
        name: 'Admin User',
        email: 'admin@hustcode.com',
      },
      _count: {
        problems: 5,
        participants: 95,
      },
    },
    {
      id: 'contest-5',
      title: 'Private Team Practice',
      description: 'Private contest for team practice.',
      startTime: '2026-01-10T08:00:00.000Z',
      endTime: '2026-01-10T12:00:00.000Z',
      status: 'UPCOMING',
      isPublic: false,
      createdAt: '2025-12-30T15:00:00.000Z',
      updatedAt: '2025-12-30T15:00:00.000Z',
      createdBy: {
        id: 'user-2',
        name: 'Contest Admin',
        email: 'contest@hustcode.com',
      },
      _count: {
        problems: 3,
        participants: 20,
      },
    },
  ],
  total: 5,
  page: 1,
  pageSize: 20,
  totalPages: 1,
};

// Mock data for contest detail with problems
export const mockContestDetailData: ContestDetail = {
  id: 'contest-2',
  title: 'New Year Coding Challenge',
  description: 'Celebrate the new year with exciting coding challenges!',
  startTime: '2026-01-01T00:00:00.000Z',
  endTime: '2026-01-01T06:00:00.000Z',
  status: 'RUNNING',
  isPublic: true,
  createdAt: '2025-12-25T08:00:00.000Z',
  updatedAt: '2025-12-31T23:59:00.000Z',
  createdBy: {
    id: 'user-1',
    name: 'Admin User',
    email: 'admin@hustcode.com',
  },
  _count: {
    problems: 6,
    participants: 250,
  },
  problems: [
    {
      id: 'prob-1',
      title: 'Two Sum',
      description: 'Find two numbers that add up to a target.',
      difficulty: 'EASY',
      order: 1,
      points: 100,
      tags: [
        { id: 'tag-1', name: 'array' },
        { id: 'tag-2', name: 'hash-table' },
      ],
      _count: { submissions: 150 },
    },
    {
      id: 'prob-2',
      title: 'Valid Parentheses',
      description: 'Check if parentheses are valid.',
      difficulty: 'EASY',
      order: 2,
      points: 100,
      tags: [
        { id: 'tag-3', name: 'stack' },
        { id: 'tag-4', name: 'string' },
      ],
      _count: { submissions: 120 },
    },
    {
      id: 'prob-3',
      title: 'Longest Substring Without Repeating Characters',
      description: 'Find the longest substring without repeating characters.',
      difficulty: 'MEDIUM',
      order: 3,
      points: 200,
      tags: [
        { id: 'tag-5', name: 'sliding-window' },
        { id: 'tag-4', name: 'string' },
      ],
      _count: { submissions: 95 },
    },
    {
      id: 'prob-4',
      title: 'Merge Intervals',
      description: 'Merge overlapping intervals.',
      difficulty: 'MEDIUM',
      order: 4,
      points: 200,
      tags: [
        { id: 'tag-1', name: 'array' },
        { id: 'tag-6', name: 'sorting' },
      ],
      _count: { submissions: 80 },
    },
    {
      id: 'prob-5',
      title: 'Trapping Rain Water',
      description: 'Calculate how much water can be trapped.',
      difficulty: 'HARD',
      order: 5,
      points: 300,
      tags: [
        { id: 'tag-1', name: 'array' },
        { id: 'tag-7', name: 'two-pointers' },
        { id: 'tag-8', name: 'dynamic-programming' },
      ],
      _count: { submissions: 45 },
    },
    {
      id: 'prob-6',
      title: 'Regular Expression Matching',
      description: 'Implement regular expression matching with . and *.',
      difficulty: 'HARD',
      order: 6,
      points: 300,
      tags: [
        { id: 'tag-4', name: 'string' },
        { id: 'tag-8', name: 'dynamic-programming' },
        { id: 'tag-9', name: 'recursion' },
      ],
      _count: { submissions: 30 },
    },
  ],
};

// Mock data for contest submissions
export const mockContestSubmissionsData: ContestSubmissionsResponse = {
  data: [
    {
      id: 'sub-1',
      userId: 'user-10',
      problemId: 'prob-1',
      contestId: 'contest-2',
      sourceCode: 'function twoSum(nums, target) { ... }',
      status: 'ACCEPTED',
      executionTime: 45,
      memoryUsed: 42000,
      createdAt: '2026-01-01T00:15:00.000Z',
      user: {
        id: 'user-10',
        name: 'John Doe',
        email: 'john@example.com',
      },
      problem: {
        id: 'prob-1',
        title: 'Two Sum',
        order: 1,
      },
      language: {
        id: 'lang-1',
        name: 'JavaScript',
        version: 'Node.js 18',
      },
    },
    {
      id: 'sub-2',
      userId: 'user-11',
      problemId: 'prob-1',
      contestId: 'contest-2',
      sourceCode: 'def two_sum(nums, target): ...',
      status: 'WRONG_ANSWER',
      executionTime: 52,
      memoryUsed: 38000,
      createdAt: '2026-01-01T00:20:00.000Z',
      user: {
        id: 'user-11',
        name: 'Jane Smith',
        email: 'jane@example.com',
      },
      problem: {
        id: 'prob-1',
        title: 'Two Sum',
        order: 1,
      },
      language: {
        id: 'lang-2',
        name: 'Python',
        version: '3.11',
      },
    },
    {
      id: 'sub-3',
      userId: 'user-12',
      problemId: 'prob-3',
      contestId: 'contest-2',
      sourceCode: '#include <iostream>...',
      status: 'TIME_LIMIT_EXCEEDED',
      executionTime: 2000,
      memoryUsed: 65000,
      createdAt: '2026-01-01T01:00:00.000Z',
      user: {
        id: 'user-12',
        name: 'Bob Wilson',
        email: 'bob@example.com',
      },
      problem: {
        id: 'prob-3',
        title: 'Longest Substring Without Repeating Characters',
        order: 3,
      },
      language: {
        id: 'lang-3',
        name: 'C++',
        version: 'GCC 11.2',
      },
    },
    {
      id: 'sub-4',
      userId: 'user-10',
      problemId: 'prob-2',
      contestId: 'contest-2',
      sourceCode: 'public class Solution { ... }',
      status: 'ACCEPTED',
      executionTime: 35,
      memoryUsed: 45000,
      createdAt: '2026-01-01T00:45:00.000Z',
      user: {
        id: 'user-10',
        name: 'John Doe',
        email: 'john@example.com',
      },
      problem: {
        id: 'prob-2',
        title: 'Valid Parentheses',
        order: 2,
      },
      language: {
        id: 'lang-4',
        name: 'Java',
        version: '17',
      },
    },
    {
      id: 'sub-5',
      userId: 'user-13',
      problemId: 'prob-5',
      contestId: 'contest-2',
      sourceCode: 'func trap(height []int) int { ... }',
      status: 'RUNTIME_ERROR',
      executionTime: null,
      memoryUsed: null,
      createdAt: '2026-01-01T02:30:00.000Z',
      user: {
        id: 'user-13',
        name: 'Alice Brown',
        email: 'alice@example.com',
      },
      problem: {
        id: 'prob-5',
        title: 'Trapping Rain Water',
        order: 5,
      },
      language: {
        id: 'lang-5',
        name: 'Go',
        version: '1.21',
      },
    },
  ],
  total: 5,
  page: 1,
  pageSize: 20,
  totalPages: 1,
};
